typography_spectrum: 0.3488880281802267
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.19431712431833148
  lightness: 0.5974820877891034
  saturation: 0.49424989707767963
  rhythmicContrast: 0.4456598265096545
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6626404395792633
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Cam
  email: cam@cam.org.uk
name: TheBlogOfCam
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Pictures of Cars!
    id: dc0e33a1-7afc-4e38-8674-75f6acb41780
    type: content
favicon: null
title: ''
description: ''
purpose: []
