name: TheBlogOfCam
favicon: null
layout_spectrum: 0.144701327662915
typography_spectrum: 0.9841507135424763
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.19431712431833148
  lightness: 0.5974820877891034
  saturation: 0.49424989707767963
  rhythmicContrast: 0.4456598265096545
purpose: []
